services:
  frontend:
    image: inductiveautomation/ignition:8.1.45
    hostname: frontend
    ports:
      - 9088:8088
    volumes:
      - frontend-data:/usr/local/bin/ignition/data
    networks:
      - frontend-network
    environment:
      - IGNITION_EDITION=standard
      - GATEWAY_ADMIN_PASSWORD=katlego
      - ACCEPT_IGNITION_EULA=Y
    command: >
      -n frontend-gateway
      -m 2048
  backend:
    image: inductiveautomation/ignition:8.1.45
    hostname: backend
    ports:
      - 9090:8088
    volumes:
      - backend-data:/usr/local/bin/ignition/data
    networks:
      - frontend-network
      - backend-network
    environment:
      - IGNITION_EDITION=standard
      - GATEWAY_ADMIN_PASSWORD=gagoopane
      - ACCEPT_IGNITION_EULA=Y
    command: >
      -n backend-gateway
      -m 1024
  db:
    image: mariadb:10.10.2
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      backend-network:
        aliases:
          - main-db
    environment:
      - MARIADB_ROOT_PASSWORD=ignition
      - MARIADB_DATABASE=ignition
      - MARIADB_USER=ignition
      - MARIADB_PASSWORD=ignition

networks:
  frontend-network:
  backend-network:
volumes:
  frontend-data:
  backend-data:
  db-data: