services:
  frontend:
    image: inductiveautomation/ignition:8.1.45
    hostname: frontend
    ports:
      - 9088:8088
    volumes:
      - frontend-data:/usr/local/bin/ignition/data
    networks:
      - frontend-network
    environment:
      - IGNITION_EDITION=standard
      - GATEWAY_ADMIN_PASSWORD=katlego
      - ACCEPT_IGNITION_EULA=Y
    command: >
      -n frontend-gateway
      -m 2048
networks:
  frontend-network:
volumes:
  frontend-data: